### ISSUE TITLE
how to get all ip_address of devices

### ISSUE THREAD

**Issue by erica-jiang** [bobthebutcher/ise#1]
From these documents,I want to know how to get all  ip_address of devices?
Thank you

**Comment by bwks** [comment]
Hi There,

I dont work with ISE anymore so this library will not be maintained unless I start a role where I work with it again.

Anyway to answer you question

```
# get a list of the devices
devices = ise.get_devices()['response']

# This will be the contents of the devices variable
[('TEST_R3', '3d52aca0-c5bc-11e5-a0ed-000c297b78b4'),
 ('TEST_R4', '2d80d6d0-c5bc-11e5-a0ed-000c297b78b4')]
```
```
# Iterate through the list of devices and print out the devices ip address.
for device in devices:
    dev = ise.get_device(device=dev[0])['response']
    print(dev['NetworkDeviceIPList']['NetworkDeviceIP']['ipaddress'])
```

Ill close this issue, feel free to issue a pull request to update the docs.

**Comment by erica-jiang** [comment]
thank you
But I use the example 。I can get some of devices not all。Can you look it？thank you






--
发自我的网易邮箱手机智能版



在 2017-12-05 17:18:14，"Brad Searle" <notifications@github.com> 写道：


Hi There,

I dont work with ISE anymore so this library will not be maintained unless I start a role where I work with it again.

Anyway to answer you question

get a list of the devices

devices = ise.get_devices()['response']

This will be the contents of the devices variable

[('TEST_R3', '3d52aca0-c5bc-11e5-a0ed-000c297b78b4'),
('TEST_R4', '2d80d6d0-c5bc-11e5-a0ed-000c297b78b4')]

Iterate through the list of devices and print out the devices ip address.

for device in devices:
dev = ise.get_device(device=dev[0])['response']
print(dev['NetworkDeviceIPList']['NetworkDeviceIP']['ipaddress'])

Ill close this issue, feel free to issue a pull request to update the docs.

**Comment by bwks** [comment]
No sorry I cannot.
