### ISSUE TITLE
GetAll devices

### ISSUE THREAD

**Issue by capitaojack** [bobthebutcher/ise#2]
Hello!

How you did treat "Get-All" queries that return more than 25 items ? ... I question because the API returns paginated and not always comes the link from the next page...I realized in tests with Postman

thanks !

**Comment by lemonhead123** [comment]
i had the same problem last week and did a quick workaround, not perfect, but it works.  here just a suggestion, you still have to adapt to yourself

[ise_next_page.txt](https://github.com/bobthebutcher/ise/files/2951382/ise_next_page.txt)

**Comment by capitaojack** [comment]
Great!!

Thanks

**Comment by bwks** [comment]
Closing this issue as I will be archiving the project.
