### ISSUE TITLE
ISE 2.4

### ISSUE THREAD

**Issue by shad977** [bobthebutcher/ise#3]
Is this still working with ISE 2.4?

I get this error when running ise.get_device_groups:

Traceback (most recent call last):
  File "C:/Users/brmmm2/PycharmProjects/DTLS/venv/Create_device.py", line 6, in <module>
    ise.get_device_groups()
  File "C:\Users\brmmm2\PycharmProjects\DTLS\ise\cream.py", line 482, in get_device_groups
    for i in ERS._to_json(resp.text)['ns3:searchResult']['resources']['resource']]
KeyError: 'resources'

I'm just testing it, here is my code:

from ise.cream import ERS

ise = ERS(ise_node="IP", ers_user='ers_admin', ers_pass='password', verify=False, disable_warnings=True)

ise.get_device_groups()

**Comment by bwks** [comment]
Hey sorry I have not used this package for years since leaving the job where I supported ISE. There is a good chance that it will not work in modern version of ISE.

**Comment by shad977** [comment]
No worries, I found a guy that is constantly updating it so it works with ise 2.4. Thank you for your work.
________________________________
